- thrift.md
Commas are optional in the Thrift definition and we have started omitting them in our definitions.
The optional versus required is personal opinion but looking at how difficult it is to backfill database fields I thought it would be good to get this in early.
> Thrift: initial advice

- AWS-costs.md
From memory I don't think it was possible to cloudform this when I originally added it to Media Atom Maker (https://github.com/guardian/media-atom-maker/pull/263) but looking at the docs it is now!
> Add example cfn to aborting multipart uploads recommendation

- security.md
Minor updates, mostly to remove reference to the SKF
This has be decommissioned and no longer exists 🔥 🔪 💀 
The circle of life continues... 🌱 🐣 🌤
> Remove reference to SKF, mention SHQ and SSM-scala

- client-side.md
This is a first step in updating these recommendations, by removing outdated or harmful rules for modern browsers.
For example "Minimize the number of HTTP requests using methods such as bundling to avoid latency issues." is less relevant (and even harmful to cache-ability) in HTTP/2 supporting browsers.
I have not added or majorly edited any recommendations.
> Remove outdated or harmful rules

- client-side.md
Here's the stuff @JamieB-gu and I put together for our `@guardian` npm packages recommendation – what do you think?
we had a further question:
- should we recommend publishing commonjs and esmodules, or just esm? @SiAdcock did you have to include cjs in source?
cc @guardian/client-side-infra  
_refs [this discussion](https://github.com/orgs/guardian/teams/client-side-infra/discussions/11) and https://github.com/guardian/dotcom-rendering/pull/1919_
> add `@guardian` packages recommendation

- security.md
Teams should have non-Janus access to their AWS accounts for use In the event of a VPN or Janus outage.
This is not a change to policy, just making the doc reflect current practice
> IAM users as Janus backup

- client-side.md
- npm-packages.md
creates a separate npm-packages doc and links back to it from the client side one.
> Create separate npm-packages doc

- github.md
In the [README](https://github.com/guardian/actions-merge-release-changes-to-protected-branch/blob/main/README.md) for the [guardian/actions-merge-release-changes-to-protected-branch action](https://github.com/guardian/actions-merge-release-changes-to-protected-branch) we provide some recommendations around repository settings for users of the action. 
This PR writes these recommendations more generally and adds them to this repository for greater visibility.
> Add recommendations around GitHub

- npm-packages.md
In the [README](https://github.com/guardian/actions-merge-release-changes-to-protected-branch/blob/main/README.md) for the [guardian/actions-merge-release-changes-to-protected-branch action](https://github.com/guardian/actions-merge-release-changes-to-protected-branch)  we provide some recommendations around tools to aid the crafting and validation of semantic commits.
This PR writes these recommendations more generally and adds them to existing recommendations around semantic release for greater visibility.
> Add recommendations for conforming commits tooling

- npm-packages.md
Running `npx` or `yarn dlx` in CI is non-deterministic.
`npx` will install the latest version of dependencies that match the requirements in the library's `package.json`. This means if the library depends on version "^1.0.0" (any minor version on the 1 major) of a library, it could resolve to 1.0.0 today and 1.99.0 tomorrow.
Installing the dependency and running it via a script is preferred as we begin to treat the library like any other dependency. That is, the resulting lockfile can be used in CI to provide a deterministic and repeatable outcome.
`@guardian/node-riffraff-artifact` was depending on `"aws-sdk": "^2.610.0"`.
The `tag-janitor` repository (among [others](https://github.com/search?q=org%3Aguardian+%22npx+%40guardian%2Fnode-riffraff-artifact%22&type=code)) is [running `npx …
> chore: Add NPM CI recommendations

- continuous-deployment.md
- continuous-integration.md
This implements @mxdvl 's recommendations on markdown improvements in #48 .
> refactor: use better markdown techniques for CI and CD recommendations

- continuous-integration.md
- Slightly modify the definition of `CI` to be more precise and linked to martin fowler's article about it.
- Put `Linting` step as a first step, `before` the actual build step
- Emphasis importance of keeping the process fast
> Improve continuous integration

- AWS.md
Add recommendations on using the `--cli-read-timeout` param for the CLI to prevent unintended multiple lambda invocations
> --cli-read-timeout to prevent AWS CLI running lambdas multiple times

- security.md
Adds  a few lines on third party dependencies, mainly highlighting the Snyk Advisor as a place to check if they're still maintained
> Add section on third party dependencies

- github.md
This PR adds a new recommendation to `github.md` around archiving unused repositories. This makes it clear for anyone looking at GitHub whether a project is still used or not. It also allows these projects to be filtered out of GitHub searches.
> Add recommendation to archive unused repositories

- continuous-integration.md
With https://github.com/guardian/actions-assume-aws-role we're now able to use GitHub Actions as a CI platform.
That is, it is now possible to upload artifacts to Riff-Raff from within GitHub Actions.
Update the CI recommendations to reflect this.
> chore: Update CI, adding GitHub Actions

- github.md
This change adds two new topics to the list of recommendations for tagging GitHub repos. 
The `testing` topic is added as the existing ones didn't sufficiently cover the use case of some repositories. 
The `production` topic has been added so that other topics (e.g. `hackday`) can be maintained when a repository is productionised.
> Add new GH topics

- emotion.md
[Emotion](https://emotion.sh) is integral to how we implement CSS at the Guardian. However it is complex, and it can be hard to configure. This change provides a set of recommendations for configuration depending on the tech choices of the team using it.
This documentation was previously in the Source component library docs simply because Source requires consumers to also use Emotion. It makes more sense as a set of general recommendations as it doesn't specifically relate to the Source component library.
> Add Emotion recommendations

- AWS.md
Recommending:
- CDK
- Tagging
- Resource import
- CD
- One S3 bucket per stage
- Private S3 buckets by default
Changes can be viewed [here](https://github.com/guardian/recommendations/blob/aa-aws-recommendations/AWS.md).
> Add more detail AWS CFN recommendations

- continuous-integration.md
Updates our recommendations in response to the deprecation of https://github.com/guardian/actions-assume-aws-role.
> Remove reference to deprecated GitHub Action

- scala.md
...to recommend Corretto as the distribution and 11 or newer LTS
versions.
A longer write-up of the rationale can be found here:
https://docs.google.com/document/d/1ZR-YnaXCT5_gLVmTCeGs0mWd3KPaAozPjQK8uUzHZ9w/edit?usp=sharing
> Update Java recommendations

- npm-packages.md
add info about changesets and the (as yet non-extistant) org `NPM_TOKEN` secret
> update info about publishing to NPM

- config.md
Adds a section to the config about ensuring that we make the config editable on deploy, rather than build or any other process.
Comes from a conversation with @OllysCoding @davidfurey and others, and thought it was worth capturing.
Read the update to the document, and see if it makes sense to future engineers.
Future engineers understand this.
> Add section to config on injecting on app start

- pull-requests.md
As a dev it's very easy, as soon as you merge a PR, to think of it as completed, and move on to the next thing. However, this is actually the most important time to check that the change is *working*!
This recommendation update aims to encourage devs to extend their mental model of the lifecycle of a PR a little further, post-merge, to take a little time to check on the change.
> Encourage devs to check their PRs after merging

- AWS-embedded-metrics.md
- AWS-lambda-metrics.md
This adds a recommendation page detailing how to use AWS Embedded Metrics format.
This is the recommended way to write to Metrics from Lambda functions or Container-based apps as it has many advantages over the other methods [Full details on that here](https://docs.google.com/document/d/1cL_t5NhO8J9Bwiu4rghoGh8i_um_sXDyKuq4COhdLEc/edit?usp=sharing)
It is however a technique that is not well known.
Recommendations cover what prerequisites you need to use this method as well as details on the format used to embed a metric within a logging request. It also contains a code snippet showing a sample logging request.
> Add page with recommendations for AWS Embedded Metric format

- emotion.md
- Fixes markdown for link to `jsxImportSource`
> Fix link to `jsxImportSource`

- client-side.md
Specify recommendations for Node.js projects
To me, it always makes sense to use the latest even-numbered version of Node, unless there is a good reason not to. 
Odd-numbered versions become unsupported more quickly than even-numbered.
Although there are newer version managers than nvm, the `.nvmrc` file is still the most prevalent and well-supported file for indicating Node.js version. `fnm`, `asdf` and `nvm` all support `.nvmrc` files
> Node.js recommendations for client side projects

- npm-packages.md
adds a section on `peerDependencies` in npm packages, in particular around how to handle them in monorepos
> add a section on NPM `peerDependencies`

- github.md
Describe the minimum setup for a GitHub user at the Guardian, as required by https://github.com/guardian/gu-who#enforced-requirements.
> docs: Add GitHub User recommendations

- secure-staff-services.md
This adds a recommendation for securing staff services developed by DevX & InfoSec and in use on many of our services to ensure the services we provide to staff on the internet are secure.
Read the documentation, and decide whether it makes sense and is a reasonable recommendation for our department.
[Preview link](https://github.com/guardian/recommendations/blob/rk/devx-infosec-secure-pattern/secure-staff-services.md).
> Add recommendation for securing staff services

- .github/PULL_REQUEST_TEMPLATE.md
The organisation template doesn't quite work here as it's intended for code changes, add a note on what to consider when adding a recommendation.
> Add a simple PR template

- dependencies.md
Add TypeScript to the list of non-semver packages.
This is [“by design”](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes) for this project.
- https://github.com/guardian/csnx/issues/461
- https://chat.google.com/room/AAAAWwBdSMs/b_xVhap5IYY
- https://docs.google.com/document/d/1Vi7m35w46F72z6n4fucsxm6i28xbmn2iMfPGM7zWGz8/edit#heading=h.vtwbgvn0qym8
> feat(dependencies): list TS as non-SemVer

- pull-requests.md
> **Note**
> This change can be [previewed here](https://github.com/guardian/recommendations/blob/325929187adfa71f92b83cf0fbadebcaecf35cbc/pull-requests.md).
This change adds some information from [a Google Doc](https://docs.google.com/document/d/1bjmO0IbAUGhTCg33ySk3yaCcXkmnI1IQJXHJ6OyxQo0/edit), so that it's tracked in VCS.
❓ This change makes the recommendation significantly longer, and thus less succinct. Does this reduce its value?
To avoid multiple sources of truth, this change is aimed at deleting a Google Doc.
> Add more detail to PR recommendations

- scheduled-jobs.md
Suggesting a new recommendation here - while debugging the issues behind https://github.com/guardian/grid-ftp/pull/13, @sihil pointed out that systemd timers have advantages over crontab jobs! They do require a bit more setup (eg separate `.service` & `.timer` files), but it sounds like we should probably prefer them, and let people know about them?
At the moment, GitHub search seems to show only a few places where we use [systemd-timers](https://github.com/search?q=org%3Aguardian+systemd+timer&type=code), whereas there are _lots_ of [`crontab`](https://github.com/search?p=2&q=org%3Aguardian+crontab&type=Code).
> Prefer systemd timers to crontab for scheduled jobs

- pull-requests.md
Having a mixture of `production`, `Production`, and `PROD` is unnecessarily complex.
Use a consistent term.
`PROD` is chosen as it also reflects our AWS resource tagging conventions, and the language used in tools such as Riff-Raff.
> Use consistent language for production

- security.md
This change links to the security-recommendations repository and moves some information from here to there, keeping some appropriate content in the public repository.
See https://github.com/guardian/security-recommendations/pull/1
> Link to security-recommendations repository

- applications.md
- continuous-integration.md
- ownership.md
Removing recommendations to use TeamCity, 
[sbt-riffraff-artifact](https://github.com/guardian/sbt-riffraff-artifact) and
[node-riffraff-artifact](https://www.npmjs.com/package/@guardian/node-riffraff-artifact)
We are encouraging teams to move to github actions ahead of the teamcity deprecation, so this should no longer be a recommendation
> **Note**
> 
> 
> Remove deprecated/EOL CI references

- scala.md
The recommendation is that Scala Steward is used for management of Scala dependencies.  I've called this *Continuous* dependency management but it isn't quite that.  That's the general direction of travel though.
I've been using Scala Steward for a while now, to the extent that I'd feel a bit lost without it.  
It's in use on a wide range of our repos and we have an in-house system for managing it.  So it seems stable and conventional enough to warrant a recommendation.  We aren't, as far as I'm aware, explicitly supporting any competitor systems.
This just brings together in one place the rationale for using it and some advice around it.
---
@rtyley as you and @jfsoul have done all the work to support Scala Steward in Guardian repos I wonder if there's anything else you think should be …
> Add notes on Scala Steward

- client-side.md
- dependencies.md
- npm-packages.md
The `dependencies`, `npm-packages` and `client-side` recommendations have been reworked so they no longer contradict each other.
Follow-up on #53 & #59.
> Clarify JS, NPM & Dependencies recommendations

- dependencies.md
Extension from https://github.com/guardian/recommendations/pull/115
- Adds reason and link for pinning deps (via @mxdvl)
- Adds an example for more context
> fix: add reason and examples for pinning deps to patch

- pull-requests.md
- Adds a paragraph on knowledge sharing in the discussion of the benefits of reviews.
- Adds a recommendation to read your code over before opening a PR, to catch low hanging fruit (e.g. common mistakes such as files which shouldn't have been committed).
There is already a line on knowledge sharing, but it emphasises the role of 'subject matter experts'. While subject matter experts have a distinctive role to play in certain reviews, I don't think that this captures the full knowledge-sharing benefits of code review, as it's practiced at The Guardian. In the new addition, I've tried to capture the fact that review provides opportunities for different kinds of learning, as well as the fact that much of this should be seen as happening among peers, and running in either direction (from …
> Code review: knowledge sharing and readiness

- pull-requests.md
This doesn't add any new recommendations. It just standardises the kind of quotation marks used for PR statuses, and adds a link to the relevant part of the gh docs for changing PR status.
h/t @mxdvl https://github.com/guardian/recommendations/pull/121#discussion_r1192579000
> Add docs link for PR status

- best-practices.md
It might be easier to review the [changes in rendered form](https://github.com/guardian/recommendations/blob/f30a93f21087abef4922676bb9dc88ccbd0fa565/best-practices.md).
Defines our best practices in tabular form.
We have a large number of best practices defined covering a vast spectrum of concerns, for example: AWS VPC usage; NPM module use; GitHub repository metadata; and AWS IAM users.
We have started to build tools to observe the adoption of these best practices. The logical extension to this, is to start flagging/alerting violations, at which point best practices become more like rules. For ease, “best practice” and “rule” will now be used interchangeably.
Currently, it is difficult to keep up to date with the rules as:
- Some of them are defined in prose within the …
> Introduce a table of best practices

- best-practice/README.md
- best-practice/definitions.ts
- best-practice/generate.sh
- best-practice/index.ts
- best-practice/types.ts
- best-practices.md
This follows on from #119.
Use [Deno](https://deno.com/) for a lightweight script to generate a Markdown table, and inject it into best-practice.md.
The TypeScript type-system allows for a schema to be created, allowing each best practice to render the same way.
In #119 I commented:
> Writing markdown tables by hand is not fun!
This is still true! I also commented:
> I'll think of a lightweight way to introduce auto-generation of these tables. Initial thinking is YAML -> Markdown. Use of YAML allows for comments, and a schema for "type-checking".
Alas, converting YAML to a Markdown table wasn't quite as simple as this Deno script. The script still provides the same benefits of allowing for comments, and type-checking.
There are two downsides to this solution:
1. A requirement to install …
> feat: Generate the best practice Markdown

- cdn.md
Following on from the retro on the [DNS misconfiguration of mobile.guardianapis.com on 2023-05-18](https://docs.google.com/document/d/1WDNxLNPAK7aWazhGnmIFwONIU7-PrgpTuKjnwh2et1c/edit?usp=sharing), here's added documentation on our preferred hostname for Fastly (`dualstack.guardian.map.fastly.net.`), as well as a bit of re-organisation and added links.
Incidentally, https://github.com/guardian/fastly-edge-cache/issues/986 may be of interest, regarding the choice of LCY as shield.
> Update Fastly doc to include preferred hostname

- RFCs.md
- architecture-decision-records.md
- github.md
This presents and briefly explain architecture decisions records, notably in the context of them being the natural long term outcome of rfcs ( https://github.com/guardian/recommendations/pull/125 ).
> explain architecture decision records

- github.md
After discussion last week with DevX, including @akash1810 & @NovemberTang, we decided to deprecate [repo-genesis](https://github.com/guardian/repo-genesis) on the grounds that:
* Not all devs are using it, many are using https://repo.new/ -  there's no benefit to maintaining/running `repo-genesis` if it's not being used
* `repo-genesis` is hosted on Heroku, which has always been difficult for us to securely manage access for, rather than hosting on AWS where we have Janus, etc
* There are many different aspects to setting a GitHub repo in the best possible way, and `repo-genesis` only enforced a couple of them, and only at the point of creation. DevX have plans to enable a new repo-monitoring service which will ensure many more aspects of Guardian repos are checked and adhere to best …
> Deprecate repo-genesis

- emotion.md
Nothing new.
- assumption of `yarn`, which may not be used by teams
- incorrect versions ranges for TS and React
- add link to new best practices for emotion
> Update Emotion documentation

- README.md
Write out the whole CAP acronym in the main README.
we’re not talking baseball here… and it took me a little bit of searching to [figure out what it meant](https://www.ibm.com/topics/cap-theorem).
I’m assuming this is related to having to pick two of:
- Consistency
- Availability
- Partition tolerance
> docs: write CAP out

- npm-packages.md
Updates the process for getting access to the organisational `NPM_TOKEN` secret, which is now automated via https://github.com/guardian/github-secret-access.
See the [README of https://github.com/guardian/github-secret-access](https://github.com/guardian/github-secret-access/blob/main/README.md).
> **Note**
> 
> 
> fix(npm): Use guardian/github-secret-access to vend NPM_TOKEN

- scala.md
Nothing new, but the Scala recommendations are refactored to focus on the solution rather that the problem.
Relegate the discussion on dependency injection to a footnote.
Focus on the preferred solution over what we do not recommend. People want to solve problems, not be told off.
Original wording in #19
Pinging @guardian/scala who may want to chime in
The bullet is more consice and contains a footnote:
Then at the bottom of the document:
> Focus on solution over problem in Scala recommendations

- inclusive-communication.md
I’ve looked for [the inclusive communication guide](https://github.com/guardian/our-engineering-culture/blob/main/inclusive-communication.md) before and found it hard to find because I always look here, forgetting it’s in another repository. I think covering ~engineering culture and~ inclusive communication in our recommendations seems like a good fit, and then the info is in one place.
(Note I’ve made minor tweaks to the files in the process of copying them over, which I’ve put in a separate commit for ease of review.)
> Copy the inclusive communication guide from our engineering culture repository

- .github/workflows/inclusion.yml
- AWS-costs.md
- AWS-lambda-metrics.md
- AWS.md
- README.md
- RFCs.md
- cdn.md
- client-side.md
- domain-names.md
- elasticsearch.md
- github.md
- inclusive-communication.md
- logging.md
- npm-packages.md
- ownership.md
- pull-requests.md
- scala.md
- scheduled-jobs.md
Language changes to make [alex](https://alexjs.com/) happier, plus a couple of grammatical fixes.
Where a language change doesn't make sense, would cause confusion, or otherwise fundamentally alter the meaning of the sentence, the warning has been ignored by adding a comment one line up.
As this fixes all outstanding issues, this PR also enables Alex properly, causing CI to fail when it detects less inclusive language
> Alex fixes

- domain-names.md
Adds a link to the CDK docs on migrating an existing NS1 record to CDK.
This is salient information for people who want to understand and implement our existing DNS recommendations, but currently is somewhat difficult to discover because it's included as a step in the migration guide. (I don't think it's separately documented elsewhere, but could be mistaken.)
> Link to CNAME migration docs

- github.md
Recommend using Apache v2 license for new public Github repos.
There is no current recommendation. This clarifies it. Based off this response from @rtyley : https://chat.google.com/room/AAAAWaoV0IE/8YD-6nXOTqg/8YD-6nXOTqg?cls=10
> Add recommendation for Apache v2 license

- pull-requests.md
The current emphasis in our recommendation regarding PR is too strong on their size, leading to creation of PRs smaller necessaries which is not very efficient. 
The associated change reduce that emphasis, explicitly mentioning that some dependencies upgrade to be grouped avoiding typical compatibility issues and bugs, and preventing people to focus on minimising number changes rather than delivering them.
> **Note**
> 
> 
>  - If it is security related, should you consult with …
> Specify that PR can combine multiple changes, especially for dependencies upgrade

- github-rulesets.md
Further to https://github.com/guardian/recommendations/pull/163, @andrew-nowak & I just realised today that unfortunately org-owner permission is required for setting custom properties on a repo.
The wording in [the GitHub docs](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/managing-custom-properties-for-repositories-in-your-organization) above is actually ambiguous about whether people with write/admin permissions on a repository can _set_ the values of custom properties for that repository - but it turns out that unfortunately they can't 😢 
@andrew-nowak is a member of the [`digital-cms-admins` team](https://github.com/orgs/guardian/teams/digital-cms-admins) and thus [has admin on the `pan-domain-authentication` …
> Clarify that org-owner permission is required for setting custom properties on a repo

- ownership.md
- snyk.md
How to get set up with Snyk.
Security HQ is being deprecated and the Snyk-related documentation has been removed from there. Moving it here as per @NovemberTang's recommendation.
> Add Snyk documentation

- accessibility.md
This is a fix for an incorrect link. `predictable` links to the `navigable` guidelines.
> Fix incorrect link in accessibility recos

- accessibility.md
Recommending the whole WCAG AA standard as our benchmark. I believe that we do currently see ourselves as accountable to WCAG AA in the department, and that we're right to do so.
If I understand correctly then the original reason for mentioning 'a subset' was to prevent the recommendation from feeling too overwhelming for readers who are new to the standard (which is quite detailed, and not always the most user-friendly for newcomers). In light of this, I've explicitly reframed the list of core principles as a starting point, which should hopefully point people in the direction of the most impactful parts of the spec, if they're new to the topic.
> **Note**
> 
> The recommendations in this repository are intended to share engineering best practices for all of Product & Engineering (P&E) …
> Reference the whole WCAG standard

- AWS.md
The NodeJs v10 and v12 runtimes are fully deprecated. See https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated. Therefore this documentation cannot be used.
I've also switched to using `#` headers over `-` to make it easier to understand the heading level.
---
See also https://github.com/guardian/recommendations/pull/42.
> docs(aws-lambda): Remove section for node 10 and 12 lambda runtime

- AWS.md
We should no longer be recommending the storing of credentials in S3, so this has been removed from `aws.md`.
For improved security.
> docs: stop recommending storing creds in S3

- ownership.md
- security.md
Replaces links to Security HQ docs which have moved to Security Recommendations repo.
Security HQ is being deprecated.
> **Note**
> 
> 
> refactor: replace links/mentions of security hq

- github.md
Since GitHub introduced [internal repositories](https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/about-repositories#about-internal-repositories), it's unclear whether `Internal` or `Private` is the best choice for new repositories.
It's also unclear what the role of the [`@guardian/guardian-developers-read`](https://github.com/orgs/guardian/teams/guardian-developers-read) team is, given the existence of internal repositories.
I've added some guidelines indicating:
1) a preference for `Internal` over `Private`
2) a preference for also granting write permissions to [`@guardian/guardian-developers-write`](https://github.com/orgs/guardian/teams/guardian-developers-write)
3) that [`@guardian/guardian-developers-read`](https://github.com/orgs/gua …
> Add notes on Internal vs Private visibility

- README.md
- publishing-libraries-to-maven-central.md
The main message is that Scala projects should use [`gha-scala-library-release-workflow`](https://github.com/guardian/gha-scala-library-release-workflow) to publish to Maven Central, as we've [standardised](https://github.com/guardian/gha-scala-library-release-workflow/issues/20) on it and it does [all the right things](https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/benefits.md):
* **achieve zero-onboarding for new developers**: Any developer who has `write` access to a repo should be able
to publish a release of the library, at the click of a button.
* **securely handle release credentials** - only allow access to release credentials for parts of the release process
that [_need_](https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/s …
> Add recommendations on Publishing libraries to Maven Central

- inclusive-communication.md
Remove the reference to a thread by Twitter engineering on Inclusive language.
Twitter is perhaps not the best source to talk about inclusive language anymore given its current leadership! I don't recommend scrolling down on the linked Twitter thread!
> Remove reference to Twitter inclusive language guidelines

- scheduled-jobs.md
Leveraging an app's load balancer to schedule tasks with side-effects on multi-instance apps.
This is a problem that my team and I have come across a few times, and describes a solution that we've found to work well in production a few times.
I presented on this approach at Server Side Meetup a couple of months ago and it was generally well-received, and I've incorporated some extra considerations that were raised in discussion into this recommendation.
> Scheduling behaviour for multi-instance apps

- scala.md
Now that scala has LTS and next, we should follow the official recommendation for our code.
https://www.scala-lang.org/development/
I also removed a couple of lines that are probably just noise nowadays.
> clarify scala version recommendation

- AWS.md
Update a link as https://github.com/guardian/private-infrastructure-config is deprecated in favour of https://github.com/guardian/aws-account-setup/blob/main/packages/shared/README.md.
> docs(AWS): Update link to AWS package
