guardian/recommendations

- AWS.md
- README.md
- security.md
Some recommendations / guidelines relating to securing our applications. These are all based on real issues we've faced and will probably be an evolving list as we find new areas of concern and best practices move on.
> Security guidelines

- security.md
Based on comments on previous PR.
cc @adamnfish
> Updates to security document

- security.md
I figured this was a good place to plug the github team keys lambda.
> Add guidance for SSH keys

- AWS-costs.md
Add info shared by email previously
> Add incomplete multipart upload for S3

- scala.md
To make it clear we do not recommend the cake pattern
@philwills
> Remove reference to the cake pattern

- resiliency.md
We don't use those terms
(see https://github.com/guardian/recommendations/issues/28)
> Remove gold/silver/bronze resiliency

- AWS.md
_@mbarton suggested I share the info from my department email in this repo, for posterity_
> some advice/discoveries about counting 5XX (backend vs ELB)

- accessibility.md
In order to improve the accessibility of our products consistently, and to ensure they continue to be accessible in the future, this change adds a few accessibility recommendations.
There might be gaps around accessibility on native apps, so I'd appreciate some advice from native apps teams on this subject. 
I'm also happy to hear suggestions for any other high level recommendations - how can we cover 80% of accessibility issues using these recommendations?
> Add accessibility recommendations 🌐

- accessibility.md
One of the goals of the design system is to help make our products accessible by providing components and patterns that adhere to accessibility best practice.
This change formally recommends product maintainers use the design system where possible to provide better guarantees around the accessibility of their products.
> Add design system section to accessibility recommendations

- security.md
Minor addition with recommendation around data retention.
Expand data handling section
NA
NA
NA
NA
> Add a note on data retention

- AWS.md
Add the workaround for socket issues with NodeJS lambdas. This isn't really a recommendation per-se but this repo is the best place I could think of to put the advice so it's not lost in chat rooms and emails
> [AWS Lambda] How to fix socket timeout issues

- accessibility.md
Adds the [Enough Time](https://www.w3.org/TR/WCAG21/#enough-time) section to the list of WCAG 2.1 guidelines that we conform to.
Enough Time includes some important guidance around:
- providing the user with an adequate amount of time to complete an action
- stopping, pausing or hiding non-essential animation
The latter recently came up in a discussion around a looping animation that appeared in a banner. Providing specific guidance on animation will help inform contributors on best practice in the future.
> Add Enough Time guideline to accessibility recommendations

- security.md
This approach has been deprecated in favour of using SSM-scala
> Remove s3-ssh-keys

- AWS.md
- Add reference to Amigo for AMIs
- Add Parameter Store as a reasonable place for credentials
> AWS updates

- client-side.md
update npm package recommendations to never publish typescript source files
> Do not not publish typescript

- npm-packages.md
Add more details and further recommendations for creating and using `@guardian` NPM packages
> Fill out npm package recommendations

- AWS.md
Recommendation to not delete S3 buckets along with the rationale behind it
> Don't delete S3 buckets

- security.md
Add some documentation to avoid a quite easy mistake that could have [a dramatic impact](https://twitter.com/esraefe/status/1397842160607711232?s=21).
> Add cache warning

- coding-with-empathy.md
this came up in a conversation with @DavidLawes this morning, and seem like good additions to this recommendation
also:
- fixes some whitespace bits (worth viewing diff [without whitespace changes](https://github.com/guardian/recommendations/compare/master...add-the-principle-of-least-surprise?quick_pull=1&w=1))
- rewrite "your" as "our"
> add reference to "the principle of least surprise"

- continuous-integration.md
> Fix typo in CI docs

- github.md
- Recommendations for the default branch name
- Recommendations for what to commit to a repository
- Recommendations on access
See the changes [here](https://github.com/guardian/recommendations/blob/aa-github/github.md).
> Update GitHub recommendations

- scala.md
The questions came today about what should be the recommended version of the `JDK`.
> Update scala recommendation

- security.md
Adds a note about infosec AWS access if Janus is unavailable.
> Add note about infosec access

- npm-packages.md
update packages recommendations to use rollup and changesets
> recommend using rollup and changesets for npm modules

- README.md
- cdn.md
Adds some recommendations on using CDNs. I don't think this is documented elsewhere.  I suspect there is a lot more useful info we could include but this seems like a reasonable starting point.
Please do question these recommendations if you disagree if them.
> Initial draft of recommendations on CDNs

- pull-requests.md
This change corrects a relative link.
> Fix link to document

- github.md
Indicate the possible (and the  recommended) method for creating a new repository in the Guardian Org.
Adapted from the original notes by @akash1810
> Notes on creating a new repository

- pull-requests.md
Further improvements to pull request recommendation written in conjunction with Akash.
Key changes are:
- avoiding implying that the author of a change remains solely responsible for it forever
- avoiding transferring unreasonable responsibility to a reviewer who has requested changes
> Pull request updates

- scala.md
> Add missing space in Scala recommendation

- dependencies.md
Recommend pinning dependencies in JavaScript applications. This ensures consistency and reliability.
https://docs.renovatebot.com/dependency-pinning/#why-pin-dependencies
> Pin JavaScript dependencies

- RFCs.md
add some best practice and rationale around RFCs.
i've encountered some confusion about what RFCs are for, what they entail and what's expected of commenters.
this is an attempt to settle on a common understanding
> Add recommendation around RFCs

- AWS.md
This adds recommendations around internal tools using `gutools.co.uk` domains. 
[This has been discussed a couple of times](https://mail.google.com/chat/u/0/#chat/space/AAAAWaoV0IE/Yf5u5YX333I), so recording it for reference.
> Add SES recommendations

- security.md
This PR includes a security recommendation to avoid the use of personally identifiable information in test or debug data.
This recommendation was written as a follow up action after a recent retrospective in P&E.
> **Note**
> 
> 
> Avoid PII in test or debug data recommendation

- npm-packages.md
This fixes the link to the example of adding Changesets.
> Fix link to changesets example

- README.md
Over time we have come with more principles that we recently collected from various internal document and presentation. We have regrouped them per area, and so it is helpful to have them added to this repository.  
Please note that those software engineering principles are technology agnostic and so we expect them to be relatively stable over time and borrowable by other organisations.
> Improve principles documentation 

- README.md
- domain-names.md
Which DNS provider to use, and which domains to use for your services. This is an attempt to codify existing practise, but at the moment is just my impression. Feedback welcome!
> First draft of domain name recommendations

- scala.md
Update the version of Java to the latest LTS. We need to update the associated doc as well, but at least this clarify the expectation.
> Upgrade version of Java from 11 to 21

- ownership.md
- security.md
- snyk.md
Using Dependabot Alerts and Dependency Graph to analyse and alert on dependency vulnerabilities.
Github is now our preferred way to track vulnerabilities.
> **Note**
> 
> 
> Update recommendations re dependency scanning

- consent-and-data-privacy.md
This is the contents of an email that the Transparency & Consent Team has sent the department periodically. I'm creating it here to have one place where we can reference it.
> Add a note about our data privacy recomendations
